'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Cyber_Crypter_Private.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to using System;
        '''using System.Collections.Generic;
        '''using System.Diagnostics;
        '''using System.Linq;
        '''using System.Net;
        '''using System.Reflection;
        '''using System.Runtime.CompilerServices;
        '''using System.Runtime.InteropServices;
        '''using System.Threading.Tasks;
        '''using System.Windows.Forms;
        '''using System.Drawing;
        '''using System.Security.Cryptography;
        '''using System.IO;
        '''using System.Text;
        '''using System.Data.OleDb;
        '''using Microsoft.Win32;
        '''using Microsoft.VisualBasic.CompilerServices;
        '''using System.Threading;
        '''
        '''//Default [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _New() As String
            Get
                Return ResourceManager.GetString("_New", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to using System;
        '''using System.IO;
        '''using System.IO.Compression;
        '''using Microsoft.VisualBasic;
        '''using System.Threading;
        '''using System.Reflection;
        '''using System.Runtime.CompilerServices;
        '''using System.Runtime.InteropServices;
        '''using System.Windows.Forms;
        '''using Microsoft.Win32;
        '''using System.Diagnostics;
        '''using System.Drawing;
        '''using System.Net;
        '''using System.Text;
        '''using System.Net.NetworkInformation;
        '''using System.Net.Sockets;
        '''using Microsoft.VisualBasic.CompilerServices;
        '''using System.Collections.Generic;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _Private() As String
            Get
                Return ResourceManager.GetString("_Private", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property cert() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cert", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;project outputDir=&quot;%path%&quot; baseDir=&quot;%basedir%&quot; xmlns=&quot;http://confuser.codeplex.com&quot;&gt;
        '''  &lt;rule pattern=&quot;true&quot; inherit=&quot;false&quot;&gt;
        '''        &lt;protection id=&quot;anti tamper&quot; /&gt;
        '''      &lt;/rule&gt;
        '''  &lt;module path=&quot;%stub%&quot;&gt;
        '''    &lt;rule pattern=&quot;true&quot; preset=&quot;none&quot; /&gt;
        '''  &lt;/module&gt;
        '''&lt;/project&gt;.
        '''</summary>
        Friend ReadOnly Property config() As String
            Get
                Return ResourceManager.GetString("config", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ConfuserEx() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfuserEx", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to using System;
        '''using System.Collections.Generic;
        '''using System.Diagnostics;
        '''using System.Linq;
        '''using System.Net;
        '''using System.Reflection;
        '''using System.Runtime.CompilerServices;
        '''using System.Runtime.InteropServices;
        '''using System.Threading.Tasks;
        '''using System.Windows.Forms;
        '''using System.Drawing;
        '''using System.Security.Cryptography;
        '''using System.IO;
        '''using System.Text;
        '''using System.Data.OleDb;
        '''using Microsoft.Win32;
        '''using Microsoft.VisualBasic.CompilerServices;
        '''using System.Threading;
        '''
        '''//Default [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Stub() As String
            Get
                Return ResourceManager.GetString("Stub", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
